### ISSUE TITLE
addTapGesture breaks Segmentio

### ISSUE THREAD

**Issue by kohdesmond** [Yalantis/Segmentio#97]
###  What did you do?
adding `self.view.addTapGesture(tapNumber: 1, target: self, action: #selector(handleTap(sender:)))`
breaks the touch for Segmentio

### What did you expect to happen?
`Segmentio.valueDidChange should be called`

### What happened instead?
the `Segmentio.valueDidChange` was not called and the touch failed

### Your Environment

- Version of the component: _insert here_
- Swift version: 4.x
- iOS version: iOS 11.x
- Device: iPhone
- Xcode version: Xcode 9.4.1

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.5 (17F77)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /Users/Desmond/.rvm/rubies/ruby-2.4.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 24f55565ef4c9949dbcd6c01aea30b983b6b3868
```

### Installation Source

```
Executable Path: /Users/Desmond/.rvm/gems/ruby-2.4.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Project that demonstrates the bug
adding `self.view.addTapGesture(tapNumber: 1, target: self, action: #selector(handleTap(sender:)))`

will break Segmentio

**Comment by rnkyr** [comment]
Hello, @kohdesmond!
Sure touch gesture brakes any nested gestures. That's an expected behavior of `UIGestureRecognizer` and is not related to the Segmentio. Consider using `touchesMoved(_:with:)` with call to `super` in order to override gestures and still support the nested one. As another option you could implement `UIGestureRecognizerDelegate` and decided whether recognizer should work for concrete view in `shouldReceiveTouch` method
